# application.yml
server:
  port: 8083

spring:
  application:
    name: UserSubscriptionService

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/user_subscriptions
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Redis Configuration
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      timeout: 2000ms
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0

# External Services Configuration
services:
  user-service:
    url: http://localhost:8081
  subscription-service:
    url: http://localhost:8082
  email-service:
    url: http://localhost:8084

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  access-token:
    expiration: 900000 # 15 minutes

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Logging Configuration
logging:
  level:
    com.example.usersubscriptionservice: DEBUG
    feign: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true